# Generated by Django 5.0.4 on 2024-05-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0003_alter_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='description',
            field=models.CharField(default='Nada.', max_length=1000),
        ),
        migrations.AddField(
            model_name='staff',
            name='image_url',
            field=models.CharField(default='logo.png', max_length=1000),
        ),
    ]
