# Generated by Django 5.0.4 on 2024-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0005_playerscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image_url',
        ),
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.CharField(default='static/logo.png', max_length=1000),
        ),
    ]
