# Generated by Django 5.0.6 on 2024-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0007_alter_staff_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.CharField(default='static/neologo.png', max_length=1000),
        ),
    ]
