# Generated by Django 5.0.6 on 2024-07-02 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='fecha',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
