# Generated by Django 5.0.6 on 2024-07-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject', '0011_follow_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fingerprint',
            field=models.IntegerField(),
        ),
    ]
